# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json



name: Infra - Feature Merge Into Main Approved - Deploy to Test Env
on: 
  pull_request:
    branches:
      - release-**
    types:
      - opened



permissions:
      id-token:               write
      contents:               read

jobs:
  # This will pick up PRs from Main, and Also Hotfix Branches Into Release
  Pull_Request_Checks:
    if:                         github.event_name == 'pull_request' && github.event.action == 'opened' && github.head_ref == 'main'
    name:                       Checks
    runs-on:                    ubuntu-latest
    steps:
      - run: |
          echo "Checks Test!!!"
      - run: |
          echo "${{ github.head_ref }}"
          echo "${{ github.base_ref }}"

  PR_Main_On_Release:
      needs: Pull_Request_Checks
      # THIS DEPENDS ON THE CHECKS ABOVE. IF THEY FAIL WE WILL NOT DEPLOY TO TEST.
      # NOTE That Hotfix Branches Will Not Deploy To UAT. Hotfixes Branches Will Be Deployed To PreProduction When HotFix Branch Merged To Release
      name:                     Infra - Feature Merge Request Into Main  - Deploy to Test Env
      runs-on:                  ubuntu-latest
      strategy:
        matrix:
          environments:          [UAT]    
    
      steps:
        - run: |
            echo "${{ github.head_ref }}"
            echo "${{ github.base_ref }}"

        - uses:                  actions/checkout@v3
          with:
            ref:                   ${{ github.head_ref }} ## THIS MUST BE MAIN AND NOT THE RELEASE

# Testing this. I want to create a boolean, which is later used in an If condition
# If there is a change to Infra (True), then run az resource deploy bash script. (run everything)
        - uses: dorny/paths-filter@v2
          id: filter
          with:
            filters: |
              workflows:
                - 'src/**'       
        
        
        - name:                 Azure Login - ${{ matrix.environments }}
          uses:                 azure/login@v1
          with:
            creds:              ${{secrets.AZURE_CREDENTIALS}}
      

        - name:                 Store JSON Param File Variables As Environ Variables
          uses:                 antifree/json-to-variables@v1.0.1
          with:
            filename:           '.github/workflows/Pipeline_Param/${{ matrix.environments }}.json'
            prefix:             param
        
        - name:                 Store BICEP Param JSON File Variables As Environ VariablesStore JSON Param File Variables As Environ Variables
          uses:                 antifree/json-to-variables@v1.0.1
          with:
            filename:           'Infrastructure/DBX_CICD_Deployment/Bicep_Params/${{ matrix.environments }}/Bicep.parameters.json'
            prefix:             param

# 5.  __Order Important__ Create Custom Role
        - name:                 Create Databricks Custom Role
          continue-on-error:    true
          run:                  bash ./.github/workflows/Utilities/Utils-Databricks-Create-Custom-Role.sh
          env:
            environment:        ${{ matrix.environments }}

        # Only run if file path !infra AND merging into main, then don't run this!
        - name:                 Deploy DBX CICD Azure Resources
          if:                   steps.filter.outputs.workflows != 'true'
          run:                  bash ./.github/workflows/Utilities/Utils-Azure-Resources.sh
          env:
            environment:        ${{ matrix.environments }}


        - name:                 Assign RBAC Permissions
          if:                   steps.filter.outputs.workflows != 'true'
          run:                  sh ./.github/workflows/Utilities/Utils-Assign-RBAC.sh
          env:
            environment:        ${{ matrix.environments }}


        - name:                 Authenticate to DBX Service Principal + Set AAD Tokens As Env Variables
          run:                  bash ./.github/workflows/Utilities/Utils-DBX-AAD-Token-Autentication.sh
          env:
            ARM_CLIENT_ID:      ${{ secrets.ARM_CLIENT_ID }}
            ARM_CLIENT_SECRET:  ${{ secrets.ARM_CLIENT_SECRET }}
            ARM_TENANT_ID:      ${{ secrets.ARM_TENANT_ID }}

            
        - name:                 Setup Python
          uses:                 actions/setup-python@v4
          with:
            python-version:     '3.8'

# 7.  __Order Important__ Set Environment Variables For Resources Created On The Fly.
        - name:                 Set Environment Variables For Resources Created On The Fly.
          run:                  bash ./.github/workflows/Utilities/Utils-Env-Variables-For-Azure-Resources-Created.sh
    

        # Update Logic To Determine If PAT Token Has Expired
        - name:                 Create And Store PAT Token In Key Vault
          run:                  bash ./.github/workflows/Utilities/Utils-Create-PAToken.sh

        - name:                 Save Databricks SP Credentials Within Secret Scopes  
          run:                  bash ./.github/workflows/Utilities/Utils-Create-Scope.sh
        
# 11.  Store Important Environment Variables In Key Vault. They Can Be Accessed Within DBUtils In Databricks via The Databricks Credentials inside the Secret Scope (above)
        #- name:                 Store Important Environment Variables In Key Vault
        #  run:                  bash ./.github/workflows/Utilities/
          
        - name:                 Create DBX Clusters
          if:                   steps.filter.outputs.workflows != 'true'
          run:                  bash ./.github/workflows/Utilities/Utils-Create-Cluster.sh
          env:
            environment:        ${{ matrix.environments }}


        - name:                 Create DBX Repos
          run:                  bash ./.github/workflows/Utilities/Utils-Create-Repo-Folders.sh
          env:
            environment:        ${{ matrix.environments }}
            PAT_GIT:            ${{ secrets.PAT_GIT }}
            ARM_CLIENT_ID:      ${{ secrets.ARM_CLIENT_ID }}


        - name:                   Install + Configure Databricks CLI
          run:                    bash ./.github/workflows/Utilities/Utils-DBX-CLI-Configure.sh

        - run: |
            echo "${{ github.head_ref }}"
            echo "${{ github.base_ref }}"

        - name:                   Create Wheel Files & Upload To DBFS
          if:                     steps.filter.outputs.workflows != 'true'
          run:                    bash ./.github/workflows/Utilities/Utils-Create-Wheels-DBFS-Cluster-Upload.sh
          env:
            environment:          ${{ matrix.environments }}

        # INCLUDE GIT PULL HERE SO THAT THE UAT ENVIRONMENT HAS THE MOST UP TO DATE VERSION OF THE MAIN BRANCH -- 
        - run: |
            echo "${{ github.head_ref }}"
            echo "${{ github.base_ref }}"

        - name:                 Update Test Repo In Test Environment (Main Branch)
          run:                  bash ./.github/workflows/Utilities/Utils-Git-Pull-DBX-Repo.sh
          env:
            BRANCH:          ${{ github.head_ref }} # Should Be Main
            UPDATE_FOLDER:  'UATFolder'
