# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json


# TO DO: Write A New Package For Setting Environment Variables From A Parameters File. 

# If Main Branch Updates, Then We Need The REPO Production Folder in ALL Environments (Production/Testing/Development) To Update
name: Main Branch Pull Request
on:  
  pull_request:
    branches:
      - main
      - develop
    types:
      - "closed"


permissions:
      id-token:               write
      contents:               read

jobs:
  DBX_CICD_Deployment:
    name:                     DBX_CICD_Deployment
    runs-on:                  ubuntu-latest
    strategy:
      matrix:
        environments:          [Development, Production]    
    steps:
      - uses:                 actions/checkout@v3  
              
      - name:                 JSON To Env
        uses:                 antifree/json-to-variables@v1.0.1
        with:
          filename:           '.github/workflows/Global_Parameters/${{ matrix.environments }}.json'
          prefix:             param

      # Switch To DBX SP
      # Day To Day Use Interacting With Databricks API Does Not Require God Rights dbxsp. The Principal of Zero Trust Applies.
      # Therefore We Use The DBX SP (Only Has Databricks Custom Role Assignments - No Owner Permissions etc), For Interacting With Databricks...
      # API To Create Clusters/ Jobs etc. Might be worth giving sp contributor right
      - name:                 Authenticate to DBX SP
        run:                  bash ./.github/workflows/Utilities/Utils-DBX-SP-Authenticate.sh
        env:
          ARM_CLIENT_ID:      ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET:  ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID:      ${{ secrets.ARM_TENANT_ID }}
      
      - run: |
          echo "${{ github.head_ref }}"
          echo "${{ github.base_ref }}"

      - name:                 Update Development Repo (Main Branch)
        run:                  bash ./.github/workflows/Utilities/Utils-Repo-Update.sh
        # What Branch is the Merge Request Being Applied To
        env:
          target_branch:             echo "${{ github.base_ref }}"




