# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Databricks Deploy
on: ["push"]
permissions:
      id-token: write
      contents: read

jobs:
  DBX_CICD_Deployment:
    name: DBX_CICD_Deployment
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environments: [Development, Test]    
    steps:
      - uses: actions/checkout@v3  
      #  az ad sp create-for-rbac -n testappciaran --role Contributor --scopes /subscriptions/4f1bc772-7792-4285-99d9-3463b8d7f994 --sdk-auth
      
      - name: 'Az CLI login ${{ matrix.environments }}'
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}

      - name: JSON To Env
        uses: antifree/json-to-variables@v1.0.1
        with:
          filename: '.github/workflows/Global_Parameters/${{ matrix.environments }}.json'
          prefix: param
            
      #- name: Deploy DBX CICD Azure Resources
      #  run: sh ./.github/workflows/Utilities/Utils-Azure-Resources.sh

      #- name: Assign RBAC Permissions 
      #  run: sh ./.github/workflows/Utilities/Utils-Assign-RBAC.sh
      #  env:
      #    environment: ${{ matrix.environments }}
      
      - name: Create And Store PAT Token In Key Vault
        run: sh "bash ./.github/workflows/Utilities/Utils-Create-PAToken.sh"
        env:
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}


