# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Databricks Deploy
on: ["push"]

jobs:
  create_resource:
    name: create_resource
    runs-on: ubuntu-latest
    strategy:
      # When order matters, then max-parallel should be set to 1
      # When order does not matter, and processes are not dependent on eachother, then remove max-parallel and they will execute in parallel 
      max-parallel: 1
      matrix:
        environments: [Development, Test, Production]
        #subscription: [Subscription1, Subscription2, Subscription3, Subscription4]
        resource_to_deploy: [workspace, PAToken, Cluster, Scope, RBAC] 
    
    steps:
      - uses: actions/checkout@v2
      
      - name: JSON To Env
        uses: antifree/json-to-variables@v1.0.1
        with:
          filename: '.github/workflows/parametersfolder/${{ matrix.environments }}.json'
          prefix: test

      - name: ${{ matrix.environments}}
        run: '.github/workflows/Utilities/Utils-${{ matrix.resource_to_deploy }}.sh'
        shell: bash
        env:
          TemplateParamFilePath: ${{ env.test_TemplateParamFilePath}} 
          TemplateFilePath: ${{ env.TemplateFilePath}} 

