# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Databricks Deploy
on: ["push"]

jobs:
  create_env_variables:
    name: Create Env Vars
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environments: [Development, Test, Production]
    
    steps:
      - uses: actions/checkout@v2
      
      - name: JSON To Env
        uses: antifree/json-to-variables@v1.0.1
        with:
          filename: '.github/workflows/parametersfolder/${{ matrix.environments }}.json'
          prefix: test

      - name: Show Output
        run: echo " Test ${{ env.test_value}} "
        with: 
          username: ${{ inputs.username }}
          token: ${{ secrets.token }}
