# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json


# TO DO: Write A New Package For Setting Environment Variables From A Parameters File. 

# If Main Branch Updates, Then We Need The REPO Production Folder in ALL Environments (Production/Testing/Development) To Update
name: Git Pull Test Environment - TestFolder
on:  
  pull_request:
    branches:
      - main
    paths-ignore:
      - src
    types: [closed, open]


permissions:
      id-token:               write
      contents:               read

jobs:
  DBX_CICD_Test:
    name:                     Git Pull Test Environment - TestFolder
    runs-on:                  ubuntu-latest
    strategy:
      matrix:
        environments:          [Development, Test]    
    steps:
      - uses:                 actions/checkout@v3  
              
      - name:                 JSON To Env
        uses:                 antifree/json-to-variables@v1.0.1
        with:
          filename:           '.github/workflows/Global_Parameters/${{ matrix.environments }}.json'
          prefix:             param

      - name:                 Authenticate to DBX SP
        run:                  bash ./.github/workflows/Utilities/Utils-DBX-SP-Authenticate.sh
        env:
          ARM_CLIENT_ID:      ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET:  ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID:      ${{ secrets.ARM_TENANT_ID }}
      
# If an Open Pull Request - Then Update the Dev Environment Only
# If A Closed Pull Request - Then Update The Test Environment
# Production Should Be Manual - There Should Be Gating
      - run: |
          echo "${{ github.head_ref }}"
          echo "${{ github.base_ref }}"