# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

# Once Feature Branch Merge Request Is Approved, The Main Branch Will Be Updated. 
# Use The Updated Main Branch Infra Code To Deploy Updated Azure Resources To UAT Environment.

name: App - Feature Merge Into Main Approved - Deploy to UAT Env
on: [workflow_dispatch] 
  #pull_request:
  #  branches:
  #    - main
  #  paths:
  #    - src/** # Include GITHUB Workflows in Time?
  #  types: [closed]

permissions:
      id-token:               write
      contents:               read

jobs:
  Git_Pull_Dev_Env:
    name:                     Git Pull UAT Environment - UATFolder
    runs-on:                  ubuntu-latest
    strategy:
      matrix:
        environments:          [UAT]    
    steps:
      - uses:                 actions/checkout@v3  
              
      - name:                 JSON To Env
        uses:                 antifree/json-to-variables@v1.0.1
        with:
          filename:           '.github/workflows/Global_Parameters/${{ matrix.environments }}.json'
          prefix:             param


      - name:                 Authenticate to DBX SP
        run:                  bash ./.github/workflows/Utilities/Utils-DBX-SP-Authenticate.sh
        env:
          ARM_CLIENT_ID:      ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET:  ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID:      ${{ secrets.ARM_TENANT_ID }}
      

      - run: |
          echo "${{ github.head_ref }}"
          echo "${{ github.base_ref }}"

      - name:                 Update Test Repo In Test Environment (Main Branch)
        run:                  bash ./.github/workflows/Utilities/Utils-Git-Pull-DBX-Repo.sh
        env:
          BRANCH:          ${{ github.base }} # Should Be Main
          UPDATE_FOLDER:  'UATFolder'

      # CREATE .WHL FILE
