# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json


# TO DO: Write A New Package For Setting Environment Variables From A Parameters File. 

name: CreateWheelFile

on: push
#workflow_dispatch

permissions:
      id-token:               write
      contents:               read

jobs:

  CreateWheel:
    name:                     CreateWheel
    runs-on:                  ubuntu-latest
    strategy:
      matrix:
        #Azure Resource Environments.
        environments:          [Development, Production]    
    steps:
      - uses:                 actions/checkout@v3  
      - name:                 Setup Python
        uses:                 actions/setup-python@v4
        with:
          python-version: '3.8'

      - name:                   Install Wheel
        run: | 
          # Install Packages

          python -m pip install --user --upgrade setuptools wheel
          sudo apt-get install pandoc
          #sudo apt-get install pdoc
          pip3 install pdoc3
          pip3 install pypandoc
          pip3 install opencensus
          pip3 install opencensus-ext-azure
          pip3 install typeguard
          pip3 install pytest
          pip3 install python-dotenv
          pip3 install jupyter
          pip3 install databricks-api
          pip3 install pandas
          pip3 install pydataset
          pip3 install pyspark 
          pip3 install requests


          # Navigate To The Setup.Py File
          ls
          cd src
          cd pipelines
          cd dbkframework


          # Create The Python Wheel File
          python setup.py sdist bdist_wheel

          # Display The New Python Wheel (dbkframework-20220727.post112208-py3-none-any.whl)
          cd dist
          echo "Name of Pyton Wheel File"
          ls


          # Install Wheel
          pip uninstall dbkframework-1-py3-none-any.whl
          pip install dbkframework-1-py3-none-any.whl





        shell: bash

      #- name:                 Upload Wheel Files To Cluster 
      #  run:                  python src/tutorial/scripts/install_dbkframework.py -c "src/tutorial/cluster_config.json"
      #  env:
      #    environment:        ${{ matrix.environments }}