# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json


# TO DO: Write A New Package For Setting Environment Variables From A Parameters File. 

name: CreateWheelFile

on: push
#workflow_dispatch

permissions:
      id-token:               write
      contents:               read

jobs:

  CreateWheel:
    name:                     CreateWheel
    runs-on:                  ubuntu-latest
    strategy:
      matrix:
        #Azure Resource Environments.
        environments:          [Development, Production]    
    steps:
      - uses:                 actions/checkout@v3  
      - name:                 Setup Python
        uses:                 actions/setup-python@v4
        with:
          python-version: '3.8'

      - name:                   Install Wheel
        run: | 
          python -m pip install --user --upgrade setuptools wheel
          sudo apt-get install pandoc
          #sudo apt-get install pdoc
          pip3 install pdoc3
          pip3 install pypandoc
          pip3 install opencensus
          pip3 install opencensus-ext-azure
          
          pip3 install requests
          ls
          cd src
          cd pipelines
          cd dbkframework

          #export PATH=”$PATH:/src/modules” 

          
          python setup.py sdist bdist_wheel

          cd dist
          ls


        shell: bash

      #- name:                 Upload Wheel Files To Cluster 
      #  run:                  python src/tutorial/scripts/install_dbkframework.py -c "src/tutorial/cluster_config.json"
      #  env:
      #    environment:        ${{ matrix.environments }}