# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
 # __  __           _            ______ _               
 # |  \/  |         | |          |  ____| |              
 # | \  / | __ _ ___| |_ ___ _ __| |__  | | _____      __
 # | |\/| |/ _` / __| __/ _ \ '__|  __| | |/ _ \ \ /\ / /
 # | |  | | (_| \__ \ ||  __/ |_ | |    | | (_) \ V  V / 
 # |_|  |_|\__,_|___/\__\___|_(_)|_|    |_|\___/ \_/\_/                                                        


name: Main
on: ["push"]


jobs:
  environment_configuration:
    strategy:
      matrix:
        environments: [Development, Test, Production]
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: JSON to Variables
        uses: antifree/json-to-variables@v1.0.1
        with:
          filename: '.github/workflows/parametersfolder/${{ matrix.environments }}.json'
          prefix: test
      
      - name: Show Output
        run: echo " Test ${{ env.test_value}} "

      - name: Test Bash Script
        run: |
          echo "This is Bash Script Test"
      

  call-workflow-in-another-repo:
    uses: ciaran28/DatabricksAutomation/.github/workflows/reusable_template.yml@main
    with:
      username: test
      environment: ${{ matrix.environments }}
    secrets: 
      token: token
