# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Main
on: ["push"]

jobs:
  build-and-test:
    strategy:
      matrix:
        environments: [Development, Test, Production]
    runs-on: ubuntu-latest
    
    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: do stuff
        run: |
          bash stuff

  call-workflow-in-another-repo:
    uses: ciaran28/DatabricksAutomation/.github/workflows/reusable_template.yml@main
    with:
      username: test
    secrets: 
      token: 123
