# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
 # __  __           _            ______ _               
 # |  \/  |         | |          |  ____| |              
 # | \  / | __ _ ___| |_ ___ _ __| |__  | | _____      __
 # | |\/| |/ _` / __| __/ _ \ '__|  __| | |/ _ \ \ /\ / /
 # | |  | | (_| \__ \ ||  __/ |_ | |    | | (_) \ V  V / 
 # |_|  |_|\__,_|___/\__\___|_(_)|_|    |_|\___/ \_/\_/                                                        


name: Main
on: ["push"]


jobs:
  create_databricks_envs:
    uses: ciaran28/DatabricksAutomation/.github/workflows/reusable_template.yml@main
    with:
      username: test
    secrets: 
      token: token
