# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Reusable workflow example

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
      environment:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  example_job:
    name: Pass input and secrets to my-action
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/my-action
        with:
          username: ${{ inputs.username }}
          token: ${{ secrets.token }}
  create_environment_variables_from_file:
    name: Grab Parameters and Store as Env Variables
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: JSON to Variables
        uses: antifree/json-to-variables@v1.0.1
        with:
          filename: '.github/workflows/parametersfolder/${{ inputs.environment }}.json'
  
      - name: Show Output
        run: echo " Test ${{ env.test_value}} "

      - name: Test Bash Script
        run: |
          echo "This is Bash Script Test"