# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json


# TO DO: Write A New Package For Setting Environment Variables From A Parameters File. 

# If Main Branch Updates, Then We Need The REPO Production Folder in ALL Environments (Production/Testing/Development) To Update
name: test
on: [push]


permissions:
      id-token:               write
      contents:               read

jobs:
  testtyt:
    name:                     Git Pull Test Environment - TestFolder
    runs-on:                  ubuntu-latest
    strategy:
      matrix:
        environments:          [Development]    
    steps:
      - uses:                 actions/checkout@v3    

      - name:                 Azure Login - ${{ matrix.environments }}
        uses:                 azure/login@v1
        with:
          creds:              ${{secrets.AZURE_CREDENTIALS}}

      - name:                 JSON To Env
        uses:                 antifree/json-to-variables@v1.0.1
        with:
          filename:           '.github/workflows/Pipeline_Param/${{ matrix.environments }}.json'
          prefix:             param
      
      - name:                 DatabricksCLI
        run: | 
          pip install databricks-cli
          adburl="https://adb-3440105635727082.2.azuredatabricks.net"
          AZ_KEYVAULT_NAME=$(az keyvault list -g $param_ResourceGroupName --query "[].name" -o tsv)
          token=$(az keyvault secret show --name "dbkstoken" --vault-name $AZ_KEYVAULT_NAME --query "value" -o tsv)
          databricks configure --token <<EOF
          $adburl
          $token
          EOF
          databricks -h 
          databricks fs ls
        shell: bash