# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json


# TO DO: Write A New Package For Setting Environment Variables From A Parameters File. 

# If Main Branch Updates, Then We Need The REPO Production Folder in ALL Environments (Production/Testing/Development) To Update
name: test
on: [workflow_dispatch]


permissions:
      id-token:               write
      contents:               read

jobs:
  testtyt:
    name:                     Git Pull Test Environment - TestFolder
    runs-on:                  ubuntu-latest
    strategy:
      matrix:
        environments:          [Development]    
    steps:
      - uses:                 actions/checkout@v3    
      
      - name:                 DatabricksCLI
        run: | 
          pip install databricks-cli
          adburl="https://adb-3440105635727082.2.azuredatabricks.net"
          token=$(az keyvault secret show --name "dbkstoken" --vault-name $AZ_KEYVAULT_NAME --query "value" -o tsv)
          databricks configure --token <<EOF
          $adburl
          $token
          EOF
          databricks -h 
          databricks fs ls
        shell: bash