# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json


#Below Is Databrick CLI Config.
# Ensure There Are No Environment Variables With The Name DATABRICKS_HOST OR DATABRICKS_TOKEN Anywhere As The System Will Grab Them. 
name: test
on: [push]


permissions:
      id-token:               write
      contents:               read

jobs:
  testtyt:
    name:                     Git Pull Test Environment - TestFolder
    runs-on:                  ubuntu-latest
    strategy:
      matrix:
        environments:          [Development]    
    steps:
      - uses:                 actions/checkout@v3    

      - name:                 Azure Login - ${{ matrix.environments }}
        uses:                 azure/login@v1
        with:
          creds:              ${{secrets.AZURE_CREDENTIALS}}

      - name:                 JSON To Env
        uses:                 antifree/json-to-variables@v1.0.1
        with:
          filename:           '.github/workflows/Pipeline_Param/${{ matrix.environments }}.json'
          prefix:             param
      
      - name:                 DatabricksCLI
        run: | 
          az config set extension.use_dynamic_install=yes_without_prompt
          az login --service-principal -u $ARM_CLIENT_ID -p $ARM_CLIENT_SECRET --tenant $ARM_TENANT_ID
          pip install databricks-cli
          
          DATABRICKS_INSTANCE="$(az databricks workspace list -g $param_ResourceGroupName --query "[].workspaceUrl" -o tsv)"
          adburl="https://$DATABRICKS_INSTANCE"
          echo $adburl
          
          AZ_KEYVAULT_NAME=$(az keyvault list -g $param_ResourceGroupName --query "[].name" -o tsv)
          token=$(az keyvault secret show --name "dbkstoken" --vault-name $AZ_KEYVAULT_NAME --query "value" -o tsv)
          echo $token
          
          databricks configure --token <<EOF
          $adburl
          $token
          EOF

          echo "test"
          databricks -h 
          databricks fs ls
        shell: bash
        env:
          ARM_CLIENT_ID:      ${{ secrets.ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET:  ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_TENANT_ID:      ${{ secrets.ARM_TENANT_ID }}